name: example
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mek_data_class: ^0.0.0

dependency_overrides:
  class_to_string:
    path: ../class_to_string
  mek_data_class:
    path: ../mek_data_class

dev_dependencies:
  mek_lints: ^0.3.0
  test: ^1.20.1

  # dart run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.1.11
  mek_data_class_generator:
    path: ../mek_data_class_generator