name: example
publish_to: 'none'

environment:
  sdk: ^3.8.0

scripts:
  # To generate .g files:
  generate-code: dart run build_runner watch --delete-conflicting-outputs --verbose

dependencies:
  collection: ^1.16.0
  mek_data_class: ^0.0.0
  json_annotation: ^4.9.0

dependency_overrides:
  class_to_string:
    path: ../class_to_string
  mek_data_class:
    path: ../mek_data_class

dev_dependencies:
  mek_lints: ^2.0.0
  test: ^1.21.6

  build_runner: ^2.8.0
  mek_data_class_generator:
    path: ../mek_data_class_generator
  json_serializable: ^6.11.1
