targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: false
          create_factory: true
          any_map: true
          checked: true
          disallow_unrecognized_keys: true
          field_rename: snake

builders:
  mek_data_class_generator:
    import: "package:mek_data_class_generator/builder.dart"
    builder_factories: ["dataClass"]
    build_extensions: {".dart": [".data_class.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]